import Data.Map (Map, fromList)
-- import qualified Control.Applicative as Map
import Data.Type.Equality (apply)
import Text.Parsec (ParseError)

-- Main datatypes

data Term = Constant String
          | Variable String
          | Attribute Term Term
          | Index Term [Term]
          | Tuple [Term]
          | Operation Term Term Term

data Literal = Positive Relation
             | Negative Relation

data Relation = Atom Term [Term]
              | Comparison Term Term Term

data Rule = Assertion [Literal]
          | Implication [Literal] [Literal]
          | Contradiction [Literal]

data Declaration = LetOrder Int String Term
                 | LetFill Int String Term
                 | LetEqual Term Term
                 | LetFunction String [Term] Term
                 | LetAttribute Term Term Term

data Statement = Declare Declaration
               | Assert Rule

data State = Store Members Values Attributes Indices Ranges Domains Images

type GroundTerm = [String]

type GroundAtom = [GroundTerm]

type Model = [GroundAtom]

-- Types used in output, reports and pretty-printing

data Error = NotAProgram
           | CyclicDependencies
           | UndefinedTerms

data Warning = EmptySort
             | UnevenIff

data Message = InvalidProgram [(Error, [String])]
             | SatisfiableInstance [Model]
             | UnsatisfiableInstance
             | WarningReport [(Warning, [String])]

data CNFAtom = Plain String | Strike String
data Clause = CNF [CNFAtom]

-- Session : parameters, flags, options

-- Type aliases that make State more readable

type Members = Map String [String]                  -- A => a1, ... ai, ... an
type Values = Map (String, String)     String       -- a.f => v 
type Attributes = Map (String, String) String       -- 
type Indices = Map (String, [String])  String       -- a[b, c] => 'a[b, c]'
type Ranges = Map String [String]                   -- Map sorts to members
type Domains = Map String [String]                  -- Map function names to domain sorts
type Images = Map String [String]                   -- Map function names to image sorts

type Clause = [String]

-- Type alias for substitutions

type Substitution = Map String String

-- Convenience functions for accessing fields of states

members :: State -> Members
members (Store mem _ _ _ _ _ _) = mem

values :: State -> Values
values (Store _ val _ _ _ _ _) = val

attributes :: State -> Attributes
attributes (Store _ _ attr _ _ _ _) = attr

indices :: State -> Indices
indices (Store _ _ _ ind _ _ _) = ind

ranges :: State -> Ranges
ranges (Store _ _ _ _ rng _ _) = rng

domains :: State -> Ranges
domains (Store _ _ _ _ _ dms _) = dms

images :: State -> Images
images (Store _ _ _ _ _ _ img) = img

-----------------------------------------------------------------------------------------

class Formulesque a where
    collect :: State -> a -> [String]    -- 
    evaluate :: State -> a -> [Clause]   -- Map P to an equivalent list of clauses
    isGround :: State -> a -> Bool       -- Decide if P contains no variable symbols

-- Reading programs from strings --------------------------------------------------------

-- Map a string to a program
read :: String -> ([Declaration], [Rule])
read program = ([], [])

-- Check if a program is valid (i.e. is acyclic and all terms are defined)
check :: ([Declaration], [Rule]) -> Bool
check (ds, rs) = False

-- Check if a program has declarations with cyclic dependencies
isAcyclic :: [Declaration] -> ([Declaration], Bool)
isAcyclic ds = ([], False)

-- Check if a program contains undefined terms
noUndefined :: [Declaration] -> ([Declaration], Bool)
noUndefined ds = ([], False)

-- Check if a string is a program (i.e. is generated by the grammar defining programs)
isProgram :: String -> Bool
isProgram text = False

-- Updating a State based on the content of declarations --------------------------------------

emptyState :: State
emptyState = Store mempty mempty mempty mempty mempty mempty mempty

-- Given a list of declarations, obtain the expected state
getState :: [Declaration] -> State
getState decls = accumulate decls emptyState

-- Fold a list of declarations and a state
accumulate :: [Declaration] -> State -> State
accumulate rest str = foldl (flip applyDeclaration) str rest

-- Apply a declaration to a state (i.e. 'update' the state to comply with the declaration)
applyDeclaration :: Declaration -> State -> State
applyDeclaration decl str = str

-- The semantics of each type of declaration ---------------------------------------------------

-- Get a generic name for the ith element of a sort
name :: String -> Int -> String
name prefix n = prefix ++ "." ++ show n

-- Get n members with generic names for a sort
fillMembers :: Int -> String -> [String]
fillMembers n prefix = [ name prefix i | i <- [1..n] ]

-- Get the assignments encoding the 'next' relation of a totally ordered sort
orderAttributes :: Int -> String -> Attributes
orderAttributes size prefix = fromList [((name prefix i, "next"), name prefix (i + 1)) | i <- [1..size] ]

-- for assignment in collect first, for assignment in collect second:
-- first = eval first state assignment
-- second = eval second state assignment
-- fromList ([ ((eval fst sub str, eval attr sub str ), eval snd sub str) | sub <- collect [fst, snd]) ]

-- 
letAttributes :: State -> Term -> Term -> Term -> Attributes
letAttributes state first attribute second = mempty

-- Evaluating terms and formulas with respect to states and substitutions --------------------------------------

collect :: State -> Statement -> [String]
collect state statement = []

evaluate :: Term -> Substitution -> State -> String
evaluate t sub str = ""

--- The semantics of each type of rule -------------------------------------------------------------------------

-- Mapping programs to SAT instances ---------------------------------------------------------------------------

-- Common embeddings / encodings -------------------------------------------------------------------------------

function :: State -> String -> [String] -> String -> [Literal]
function state name domain image = []

negation :: State -> [Literal] -> [Literal]
negation state literals = []

uniqueNameAssumption :: State -> [Literal]
uniqueNameAssumption state = []

-- Common state shorthands

-- totalOrder :: State -> Prefix -> Size -> Sort -> State'
totalOrder :: State -> String -> Integer -> 

-- Mapping instance solutions to readable models ---------------------------------------------------------------

-- CLI ---------------------------------------------------------------------------------------------------------

-- So == is value equality, =/= is value inequality, and = is UNA equality, and != is UNA inequality